import { Search } from 'heroicons-react'
import Head from 'next/head'
import {useRef} from "react"
import { useRouter } from 'next/dist/client/router';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;

   router.push(`/search?term=${term}`);
  };
  
  
  return (
    <div>
      <Head>
        <title>DARK WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className="flex flex-col items-center mt-60">
      <h1 className="text-white text-6xl font-extrabold xl:text-8xl md:text-7xl ">
        DARK<span className="text-red-600">WEB</span></h1>
      
      <div className="flex w-full mt-5 rounded-full border-2 border-gray-600
      py-3 px-5 items-center max-w-md sm:max-w-xl lg:max-w-2xl">
      <Search className="h-5 mr-3 text-red-600"/>
      <input 
      type="text" 
      ref={searchInputRef}
      className="bg-transparent text-white 
      focus:outline-none flex-grow l" /> 
      </div>
         <div className="">
         <button className="btn animate-bounce" onClick={search}>DARK SEARCH</button>
         </div>
      </form>
      
    </div>
  )
}
